Copy the old Firebase config on restore

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,7 +4,7 @@
 ### Configure environment
 
 set -o errexit    # always exit on error
-set -o pipefail   # don't ignore exit codes when piping output
+set -o pipefail   # don\'t ignore exit codes when piping output
 set -o nounset    # fail on unset variables
 unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 set -e
@@ -37,21 +37,18 @@ trap 'handle_failure' ERR
 export_env_dir $ENV_DIR
 
 ### Compile
-
-if [ -n "${FIREBASE_URL-}" ]; then
+if [ -z "${FIREBASE_ADMIN_USER-}" ]; then
+  echoerr "FIREBASE_ADMIN_USER is not present in this app's environment."
+  exit 1
+elif [ -z "${FIREBASE_ADMIN_PASS-}" ]; then
+  echoerr "FIREBASE_ADMIN_PASS is not present in this app's environment."
+  exit 1
+elif [ -n "${FIREBASE_URL-}" ]; then
   info "FIREBASE_URL is already set, nothing to do."
 elif [ -f "${CACHE_DIR}/firebase/profile.sh" ]; then
-  info "We already made a Firebase for this app"
-  source "${BUILD_DIR}/.profile.d/firebase.sh"
+  info "We already made a Firebase for this app, restoring..."
+  source "${CACHE_DIR}/firebase/profile.sh"
 else
-
-  if [ -z "${FIREBASE_ADMIN_USER-}" ]; then
-    echoerr "FIREBASE_ADMIN_USER is not present in this app's environment."
-    exit 1
-  elif [ -z "${FIREBASE_ADMIN_PASS-}" ]; then
-    echoerr "FIREBASE_ADMIN_PASS is not present in this app's environment."
-    exit 1
-  fi
 
   export FB_NAME=`get_new_firebase_name`
 
